### ISSUE TITLE
i am a newcomer and the folder is not complete,need to be create?

### ISSUE THREAD

**Issue by WhoSJackie** [mcimpoi/deep-fbanks#12]
i am a newcomer and the folder is not complete,need to be create? and how to use the gitignore file

**Comment by mcimpoi** [comment]
Could you please clarify what do you mean by "the folder is not complete"?
If you are missing the dependencies, ```git submodule update -i```

Regarding .gitignore file, I recommend reading this tutorial, and the rest on that page (e.g. beginner).[https://www.atlassian.com/git/tutorials/saving-changes/gitignore](https://www.atlassian.com/git/tutorials/saving-changes/gitignore)

**Comment by WhoSJackie** [comment]
Thank you that's what i mean.because our teacher ask us to read your paper.It is a really wonderful paper.and next i want to try myself to do the experiment,but i have't meet these file type i mean like gitgore .and i also can't find the folder you mentioned in the readme file.So that's what i mean.And thank you for your reply------------------ 原始邮件 ------------------
发件人: "Mircea Cimpoi"<notifications@github.com>
发送时间: 2019年11月15日(星期五) 凌晨1:36
收件人: "mcimpoi/deep-fbanks"<deep-fbanks@noreply.github.com>;
抄送: "WhoSJackie"<jiamianqishiwooo@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [mcimpoi/deep-fbanks] i am a newcomer and the folder is notcomplete,need to be create? (#12)



Could you please clarify what do you mean by "the folder is not complete"?
 If you are missing the dependencies, git submodule update -i
 
Regarding .gitignore file, I recommend reading this tutorial, and the rest on that page (e.g. beginner).https://www.atlassian.com/git/tutorials/saving-changes/gitignore
 
&mdash;
