### ISSUE TITLE
Out of Memory Error in ostrain

### ISSUE THREAD

**Issue by RuochenQ** [mcimpoi/deep-fbanks#2]
I got a 14 GB code(FV descriptor for DCNN on OpenSurface Dataset), which is too large to get an Out of Memory error in ostrain.m line 280: code = cat(2, code{:}) ;

But my memory space is quite large: 15GB physical memory and 14GB swap space.

How do you solve this Out of Memory problem?

**Comment by mcimpoi** [comment]
Hi! What is the size of "code" variable?  
Could you please tell me on which images / dataset are you running? 
One option would be to sample (not consider all descriptors -- take 1000 of tham, uniformly sampled).
