### ISSUE TITLE
sub2ind out of range subscript

### ISSUE THREAD

**Issue by dancivitarese** [mcimpoi/deep-fbanks#3]
Hi, when I try to run `run_experiments.m` the code I get an "out of range" in `get_dcnn_features.m` (ln130).

While running the code, I noticed that `v` and `u`, defined in `get_dcnn_features.m` (ln117) get negative values. Is that OK?

Can someone help?

Thank you,
Daniel

**Comment by rockNroll87q** [comment]
I have the same problem!
With get_dcnn_features o other features, with DTD or any database.
Any solution?

**Comment by zhanghaocol** [comment]
Same problem occurred for me.
can any one give a direction

**Comment by ghost** [comment]
Exactly the same question, I don't understand the meaning of extract the offset.
And I figure out when using Alexnet, it does't occur that problem because the layers are smaller.

**Comment by nattari** [comment]
having the same problem. anyone fixed it?

**Comment by mcimpoi** [comment]
"patched" it, hopefully; boundary effects due to resizing; some negative offsets or coords outside image bounds.

Should be fixed by b9d135264f82d4bc2c41902336f6a400c8a91bb4.
