### ISSUE TITLE
where i need to collect feature vectors before applying any encoders  

### ISSUE THREAD

**Issue by sreevasu** [mcimpoi/deep-fbanks#4]
HI,

 Please can you help me on where i need to collect feature vectors (which variable gives feature values) before applying any encoders (vlad, fisher..)

Thanking you

**Comment by mcimpoi** [comment]
os_train.m, L268-273 / (L268 - 287)
and L312 - 323 --> this is where features are extracted and encoded;

then, in get_dcnn_features L70-166 --- feature extraction.
