### ISSUE TITLE
Error using get_dcnn_features (line 58) Reference to non-existent field 'normalization'.

### ISSUE THREAD

**Issue by rockNroll87q** [mcimpoi/deep-fbanks#5]
Hi!
I setup code and dependencies as shown in README but when I run 'run_experiments.m' I get the error: 

Error using get_dcnn_features (line 58)
Reference to non-existent field 'normalization'.

The same downloading matconvnet@59463fc or last version from website.

What could be?
Thanks in advance.

**Comment by rockNroll87q** [comment]
Solved! Substituting net.normalization --> net.meta.normalization in get_dcnn_features.m and
get_rcnn_features.m.

**Comment by zhanghaocol** [comment]
thanks so much

**Comment by mcimpoi** [comment]
@rockNroll87q -- do you have a pull request for this?
I didn't maintain the code, as I am planning to move it to python.

**Comment by rockNroll87q** [comment]
Hi! I solved this problem in particular, but I had also other problems without solution.
If you planned to move the code in python: so great! Looking forward to hearing from you!

**Comment by mcimpoi** [comment]
Fixed with b9d135264f82d4bc2c41902336f6a400c8a91bb4 commit; hopefully the other issues as well. No progress on python implementation.
