### ISSUE TITLE
Error in get_dcnn_features while parsing arguments in vl_argparse.m

### ISSUE THREAD

**Issue by IAmUnbounded** [mcimpoi/deep-fbanks#8]
When i run the code i get this error which is generated in line 74 of the vl_argparse.m file.
"The value of parameters in structure in args but not a structure in opts".
I am trying to solve this issue from a long time. i am running on dtd dataset and the cpu version. Please help me

**Comment by mcimpoi** [comment]
Fixed with commit b9d135264f82d4bc2c41902336f6a400c8a91bb4.
The issue was due to passing a struct for one of the fields in opts, in vl_argparse.
