### ISSUE TITLE
Error using vl_argparse

### ISSUE THREAD

**Issue by IAmUnbounded** [mcimpoi/deep-fbanks#9]
(I am facing this error when I run the run_experiments.m file) Please suggest how to tackle this error
![screenshot from 2017-09-30 21-12-46](https://user-images.githubusercontent.com/16850531/31156166-4bc3d630-a8d0-11e7-9a0e-1db7fb98c7f9.png)

**Comment by mcimpoi** [comment]
Should be fixed by commit b9d135264f82d4bc2c41902336f6a400c8a91bb4 
The issue was due to passing one struct argument in vl_argparse.

Not the most clean solution, but check the compatibility folder.
